//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesCatalog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieGenres
    {
        public int Id { get; set; }
        public int MovieId { get; set; }
        public int GenreId { get; set; }
    
        public virtual Genres Genres { get; set; }
        public virtual Movies Movies { get; set; }
    }
}
